street_names_replacements_after_sort = {
    "Allee": "Allée",
    "’": "'",
    "Residence": "Résidence",
    "Marechal": "Maréchal",
    "Rene": "René",
    "Jean Jacques": "Jean-Jacques",
    "Helene": "Hélène",
    "Ambroise Pare": "Ambroise Paré",
    "Carrieres": "Carrières",
    "Honore": "Honoré",
    "Lenine": "Lénine",
    "Crimee": "Crimée",
    "de la Cote d'Or": "de la Côte d'Or",
    "Vallee": "Vallée",
    "Benoit": "Benoît",
    "Saint Germain": "Saint-Germain",
    "Andre": "André",
    "Negrier": "Négrier",
    "Chenier": "Chénier",
    "Beéthoven": "Beethoven",
    "Prolongee": "Prolongée",
    "Felix": "Félix",
    "Eboue": "Eboué",
    "Jules Valles": "Jules Vallès",
    "Matteoti": "Mattéoti",
    "Severine": "Séverine",
    "Bruyeres": "Bruyères",
    "Chenes": "Chênes",
    "Reveil Matin": "Réveil Matin",
    "General": "Général",
    "Humanite": "Humanité"
}